/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFondo.java
 *
 * Created on 01/10/2010, 11:29:24 AM
 */

package Imagenes;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author JESUK
 */
public class JFondo2 extends javax.swing.JPanel {

     JFrame j;

    /** Creates new form JFondo */
    public JFondo2() {
        initComponents();
    }

     public JFondo2(JFrame f) {
        initComponents();
        j=f;
        Dimension h=j.getSize();//diemnsiones de la ventana
        this.setSize(h.width,h.height);//width ->ancho
                                       //height ->altura
    }

    public void paintComponent(Graphics g){
        Dimension tamanio = j.getSize();
        setSize(tamanio.width,tamanio.height);
        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/Imangenes/Eureka.png"));
        g.drawImage(imagenFondo.getImage(), 0, 0,tamanio.width, tamanio.height, null);
        setOpaque(false);
        super.paintComponent(g);
    }

    /*
     public Panel(String nombre) {
        initComponents();
        imagen= new ImageIcon(getClass().getResource(nombre));
        setSize(imagen.getIconWidth(),imagen.getIconHeight());

    }

    @Override
    public void paintComponents(Graphics g) {
        Dimension d=getSize();
        g.drawImage(imagen.getImage(),0,0, d.width,d.height,this);
       setOpaque(false);
       super.paintComponents(g);
    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
