/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmListaCuenta.java
 *
 * Created on 14-jul-2012, 11:40:57
 */
package presentacion;
import entidades.Cuenta;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import logica.*;

/**
 *
 * @author jefferson
 */
public class FrmListaCuenta extends javax.swing.JFrame {

    /** Creates new form FrmListaCuenta */
    public FrmListaCuenta(JFrame parent) {
        initComponents();
        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        tblCuenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTAR CUENTA");

        btnSalir.setFont(new java.awt.Font("Vrinda", 0, 14));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Vrinda", 0, 14));
        btnListar.setText("Listar Cuentas");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        tblCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Codigo Moneda", "Codigo Sucursal", "Codigo Empleado", "Codigo cliente", "Saldo", "Fecha", "Estado", "costo Mov.", "Clave"
            }
        ));
        scroll.setViewportView(tblCuenta);

        jLabel1.setFont(new java.awt.Font("Vrinda", 1, 18));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("LISTAR CUENTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar)
                    .addComponent(btnSalir))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        String fecha;
        GregorianCalendar fechaC;
        modelo = new DefaultTableModel();
        ArrayList<Cuenta> cuentas = new ArrayList<Cuenta>();
        cuentas = new CuentaBL().listarCuenta();
        String columnas[] = {"Codigo", "CodigoM","codigoS","codigoE","codigoC","saldo","fecha","estado","costMovimiento","clave"};
        Iterator<Cuenta> iterador = cuentas.iterator();
        modelo.setColumnIdentifiers(columnas);
        Object fila[] = new Object[columnas.length];
        Cuenta cuenta = null;
        while(iterador.hasNext()) {
            cuenta= iterador.next();
            fila[0] = cuenta.getCodigo();
            fila[1] = cuenta.getCodigoM();
            fila[2] = cuenta.getCodigoS();
            fila[3] = cuenta.getCodigoE();
            fila[4] = cuenta.getCodigoC();
            fila[5] = cuenta.getSaldo();
            fecha="";
            fechaC=cuenta.getFecha();
            fecha +=fechaC.get(Calendar.DAY_OF_MONTH)+"/";
            fecha +=(fechaC.get(Calendar.MONTH)+1)+"/";
            fecha +=(fechaC.get(Calendar.YEAR)+1900);
            fila[6] = fecha;
            fila[7] = cuenta.getEstado();
            fila[8] = cuenta.getCostMovimiento();
            fila[9] = cuenta.getClave();
            modelo.addRow(fila);
        }
        tblCuenta.setModel(modelo);
}//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
//      public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new FrmListaCuenta(null).setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tblCuenta;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo;
}
