/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmListarAsignado.java
 *
 * Created on 10/07/2012, 08:31:52 PM
 */
package presentacion;
import entidades.Asignado;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import logica.AsignadoBL;

/**
 *
 * @author Sara Rojas
 */
public class FrmListarAsignado extends javax.swing.JFrame {

    
    private static FrmListarAsignado obj=null;
    
    public static FrmListarAsignado getInstanciaUnica() {

        if (obj == null) {
            obj = new FrmListarAsignado(obj);
        }
        return obj;
    }
    /**
     * Creates new form FrmSucursal
     */
    private FrmListarAsignado(JFrame frmPrincipal) {
        initComponents();
        setLocationRelativeTo(frmPrincipal);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsignado = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnListarAsignado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..::LISTADO DE ASIGNADO::..");

        tblAsignado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "CÓDIGO SUCURSAL", "CÓDIGO EMPLEADO", "FECHA ALTA", "FECHA BAJA"
            }
        ));
        jScrollPane1.setViewportView(tblAsignado);

        btnSalir.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 102, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnListarAsignado.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        btnListarAsignado.setForeground(new java.awt.Color(0, 102, 0));
        btnListarAsignado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listar.png"))); // NOI18N
        btnListarAsignado.setText("LISTAR");
        btnListarAsignado.setToolTipText("");
        btnListarAsignado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListarAsignado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListarAsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAsignadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnListarAsignado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListarAsignado)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

    private void btnListarAsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAsignadoActionPerformed
        // TODO add your handling code here:
        modelo = new DefaultTableModel();
        String columnas[] = {"Código de asignado", "Código de sucursal", "Código de empleado",
        "Fecha Alta", "Fecha Baja"};
        Object fila[] = new Object[columnas.length];
        ArrayList<Asignado> lista = new ArrayList<Asignado>();
        lista = new AsignadoBL().listarAsignado();
        modelo.setColumnIdentifiers(columnas);
        Iterator<Asignado> iterador = lista.iterator();
        Asignado asignado=null;
        GregorianCalendar fechaA, fechaB;
        String fecha;
        int dia, mes, año;
        while(iterador.hasNext()) {
            asignado = iterador.next();
            fila[0] = asignado.getAsigcodigo();
            fila[1] = asignado.getSucucodigo();
            fila[2] = asignado.getEmplcodigo();
            fecha="";
                fechaA=asignado.getFechaAlta();
                dia = fechaA.get(Calendar.DAY_OF_MONTH);
                mes = fechaA.get(Calendar.MONTH)+1;
                año = fechaA.get(Calendar.YEAR)+1900;
                fecha+=(dia<=9?"0"+dia:dia)+"/";
                fecha+=(mes<=9?"0"+mes:mes)+"/"+año;
                fila[3]=fecha;
                fecha="";
                fechaB=asignado.getFechaBaja();

                if (fechaB!=null){
                    dia = fechaB.get(Calendar.DAY_OF_MONTH);
                    mes = fechaB.get(Calendar.MONTH)+1;
                    año = fechaB.get(Calendar.YEAR)+1900;
                    fecha+=(dia<=9?"0"+dia:dia)+"/";
                    fecha+=(mes<=9?"0"+mes:mes)+"/"+año;
                    fila[4]=fecha;
                } else{
                    fecha="null";
                    fila[4]=fecha;
                }
            modelo.addRow(fila);
        }
        tblAsignado.setModel(modelo);
    }//GEN-LAST:event_btnListarAsignadoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmListarAsignado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmListarAsignado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmListarAsignado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmListarAsignado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new FrmListarAsignado(null).setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarAsignado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAsignado;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo;
}
