/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultasEurekaBank.java
 *
 * Created on 10/08/2011, 02:21:44 PM
 */

package consultaEurekaBank;
import javax.swing.table.TableColumn;
import Imagenes.JFondo2;
import accesoADatos.SucursalDAL;
import cliente.ListarClientes;
import empleado.ListarEmpleados;
import entidades.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import negocio.*;
import reportes.ReportesS;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author David
 */
public class ConsultasEurekaBank extends javax.swing.JFrame {

    /** Creates new form ConsultasEurekaBank */
    public ConsultasEurekaBank() {
        initComponents();
        setLocationRelativeTo(null);
        JFondo2 p=new JFondo2(this);
        this.add(p,BorderLayout.CENTER);
        this.pack();
    }

     public void MostrarMovimientos(ArrayList<Movimiento> list){
         Iterator<Movimiento> iterador=list.iterator();
          JTable TablaPer= new JTable();
        DefaultTableModel model= new DefaultTableModel();
        String Col[]= { "Codigo","Num. Movimientos","Cod. Empleado","Tipo Movimiento", "Fecha", "Importe", "Cuenta Referencia"};
        model.setColumnIdentifiers(Col);
        Object fila[] = new Object[Col.length];
        Movimiento movimiento=null;
        while(iterador.hasNext()){
            movimiento =iterador.next();
            fila[0] = movimiento.getCuenCodigo();
            fila[1] = movimiento.getMoviNumero();
            fila[2] = movimiento.getEmplCodigo();
            fila[3] = movimiento.getTipoCodigo();
            fila[4] = movimiento.getMoviFecha2();
            fila[5] = movimiento.getMoviimporte();
            fila[6] = movimiento.getCuenReferencia();
            model.addRow(fila);
        }
        TablaPer.setModel(model);
        TableColumn  Colum=TablaPer.getColumn(Col[1]);
        Colum.setPreferredWidth(100);
        Colum=TablaPer.getColumn(Col[2]);
        Colum.setPreferredWidth(100);
        Colum=TablaPer.getColumn(Col[3]);
        Colum.setPreferredWidth(100);
        Colum=TablaPer.getColumn(Col[6]);
        Colum.setPreferredWidth(100);
        JScrollPane scroll= new JScrollPane(TablaPer);
        scroll.setPreferredSize(new Dimension(800,600));
        showMessageDialog(null,scroll,"Tabla", 1);
    }



     public void MostrarSucursales(ArrayList<Sucursal> list){
         Iterator<Sucursal> iterador=list.iterator();
          JTable TablaPer= new JTable();
        DefaultTableModel model= new DefaultTableModel();
        String Col[]= { "Codigo","Nombre", "Ciudad", "Direccion", "Cant.Cuenta"};
        model.setColumnIdentifiers(Col);
        Object fila[] = new Object[Col.length];
        Sucursal sucursal=null;
        while(iterador.hasNext()){
            sucursal =iterador.next();
            fila[0] = sucursal.getCodigo();
            fila[1] = sucursal.getNombre();
            fila[2] = sucursal.getCiudad();
            fila[3] = sucursal.getDireccion();
            fila[4] = sucursal.getContadorCuenta();
            model.addRow(fila);
        }
        TablaPer.setModel(model);
        TableColumn Colum=TablaPer.getColumn(Col[1]);
        Colum.setPreferredWidth(100);
        Colum=TablaPer.getColumn(Col[3]);
        Colum.setPreferredWidth(170);
        JScrollPane scroll= new JScrollPane(TablaPer);
        showMessageDialog(null,scroll,"Tabla", 1);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jmConsultaEmpleados = new javax.swing.JMenuItem();
        jmlistarEmpleados = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmConsultaClientes = new javax.swing.JMenuItem();
        jmListarClientes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmConsultaSucursal = new javax.swing.JMenuItem();
        jmListarSucursales = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmConsultaCuentas = new javax.swing.JMenuItem();
        jmListarCuentas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmConsultaMomientos = new javax.swing.JMenuItem();
        jmlistarmovimientos = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador-EurekaBank");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuBar1.setForeground(new java.awt.Color(0, 0, 204));

        jMenu1.setForeground(new java.awt.Color(0, 0, 204));
        jMenu1.setText("TABLAS");

        jMenu6.setForeground(new java.awt.Color(0, 51, 204));
        jMenu6.setText("EMPLEADOS");

        jmConsultaEmpleados.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmConsultaEmpleados.setText("Consulta Empleados");
        jmConsultaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaEmpleadosActionPerformed(evt);
            }
        });
        jMenu6.add(jmConsultaEmpleados);

        jmlistarEmpleados.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmlistarEmpleados.setText("listarEmpleados");
        jmlistarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlistarEmpleadosActionPerformed(evt);
            }
        });
        jMenu6.add(jmlistarEmpleados);

        jMenu1.add(jMenu6);

        jMenu7.setForeground(new java.awt.Color(0, 51, 204));
        jMenu7.setText("CLIENTES");

        jmConsultaClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmConsultaClientes.setText("Consulta Clientes");
        jmConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaClientesActionPerformed(evt);
            }
        });
        jMenu7.add(jmConsultaClientes);

        jmListarClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmListarClientes.setText("Listar Clientes");
        jmListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarClientesActionPerformed(evt);
            }
        });
        jMenu7.add(jmListarClientes);

        jMenu1.add(jMenu7);

        jMenu5.setForeground(new java.awt.Color(0, 51, 204));
        jMenu5.setText("SUCURSALES");

        jmConsultaSucursal.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmConsultaSucursal.setText("Consulta Sucursal");
        jmConsultaSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaSucursalActionPerformed(evt);
            }
        });
        jMenu5.add(jmConsultaSucursal);

        jmListarSucursales.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmListarSucursales.setText("Listar Sucursales");
        jmListarSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarSucursalesActionPerformed(evt);
            }
        });
        jMenu5.add(jmListarSucursales);

        jMenu1.add(jMenu5);

        jMenu3.setForeground(new java.awt.Color(0, 51, 204));
        jMenu3.setText("CUENTA");

        jmConsultaCuentas.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmConsultaCuentas.setText("Consulta Cuentas");
        jmConsultaCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaCuentasActionPerformed(evt);
            }
        });
        jMenu3.add(jmConsultaCuentas);

        jmListarCuentas.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmListarCuentas.setText("Listar Cuentas");
        jmListarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarCuentasActionPerformed(evt);
            }
        });
        jMenu3.add(jmListarCuentas);

        jMenu1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 51, 204));
        jMenu4.setText("MOVIMIENTO");

        jmConsultaMomientos.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmConsultaMomientos.setText("Consulta Movimintos");
        jmConsultaMomientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaMomientosActionPerformed(evt);
            }
        });
        jMenu4.add(jmConsultaMomientos);

        jmlistarmovimientos.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jmlistarmovimientos.setText("Listar Movimientos");
        jmlistarmovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlistarmovimientosActionPerformed(evt);
            }
        });
        jMenu4.add(jmlistarmovimientos);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu9.setForeground(new java.awt.Color(0, 0, 204));
        jMenu9.setText("REPORTES");

        jMenuItem1.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jMenuItem1.setText("AbrirReportes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        jMenuBar1.add(jMenu9);

        jMenu2.setForeground(new java.awt.Color(0, 0, 204));
        jMenu2.setText("SALIR");

        jMenuItem5.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmListarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarCuentasActionPerformed
        // TODO add your handling code here:

        listar=new CuentaBL().listarCuenta();
        MostrarCuentas(listar);


    }//GEN-LAST:event_jmListarCuentasActionPerformed

    private void jmlistarmovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlistarmovimientosActionPerformed
        // TODO add your handling code here:

       listar= new MovimientoBL().listarMovimiento();
        MostrarMovimientos(listar);
    }//GEN-LAST:event_jmlistarmovimientosActionPerformed

    private void jmConsultaCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaCuentasActionPerformed
        // TODO add your handling code here:
        ConsultaCuentas C= new ConsultaCuentas();
        C.setVisible(true);
    }//GEN-LAST:event_jmConsultaCuentasActionPerformed

    private void jmConsultaMomientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaMomientosActionPerformed
        // TODO add your handling code here:
        ConsultaMovimiento Cm= new ConsultaMovimiento();
        Cm.setVisible(true);
    }//GEN-LAST:event_jmConsultaMomientosActionPerformed

    private void jmConsultaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaEmpleadosActionPerformed
        // TODO add your handling code here:
        ConsultaEmpleado ConsultE= new ConsultaEmpleado();
        ConsultE.setVisible(true);
    }//GEN-LAST:event_jmConsultaEmpleadosActionPerformed

    private void jmConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaClientesActionPerformed
        // TODO add your handling code here:
        ConsultaClientes ConsulC= new ConsultaClientes();
        ConsulC.setVisible(true);
    }//GEN-LAST:event_jmConsultaClientesActionPerformed

    private void jmListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarClientesActionPerformed
        // TODO add your handling code here:
        ListarClientes listCli= new ListarClientes();
        listCli.setVisible(true);

    }//GEN-LAST:event_jmListarClientesActionPerformed

    private void jmlistarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlistarEmpleadosActionPerformed
        // TODO add your handling code here:
        ListarEmpleados listE= new ListarEmpleados();
         listE.setVisible(true);
    }//GEN-LAST:event_jmlistarEmpleadosActionPerformed

    private void jmConsultaSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaSucursalActionPerformed
        // TODO add your handling code here:
        ConsultaSucursales conSc= new ConsultaSucursales();
        conSc.setVisible(true);
        
    }//GEN-LAST:event_jmConsultaSucursalActionPerformed

    private void jmListarSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarSucursalesActionPerformed
        // TODO add your handling code here:
        listar=new SucursalDAL().listarSucursal();
        MostrarSucursales(listar);

    }//GEN-LAST:event_jmListarSucursalesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ReportesS repot= new ReportesS();
        repot.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();//Con esta instruccion cierras la ventana actual y liberas los recursos que esta ventana esta ocupando.

    }//GEN-LAST:event_jMenuItem5ActionPerformed

     public void MostrarCuentas(ArrayList<Cuenta> list){
         Iterator<Cuenta> iterador=list.iterator();
          JTable TablaPer= new JTable();
        DefaultTableModel model= new DefaultTableModel();
        String Col[]= { "Codigo","Codig. Moneda","Codigo Sucursal","Cod. Empleado", "Cod. Cliente", "Saldo", "Fecha ", "Estado","Monto","Clave"};
        model.setColumnIdentifiers(Col);
        Object fila[] = new Object[Col.length];
        Cuenta cuenta=null;
        while(iterador.hasNext()){
            cuenta =iterador.next();
            fila[0] = cuenta.getCuenCodigo();
            fila[1] = cuenta.getMoneCodigo();
            fila[2] = cuenta.getSucuCodigo();
            fila[3] = cuenta.getEmplCreaCuenta();
            fila[4] = cuenta.getClieCodigo();
            fila[5] = cuenta.getCuenSaldo();
            fila[6] = cuenta.getCuenFechaCreacion2();
            fila[7] = cuenta.getCuenEstado();
            fila[8] = cuenta.getCuenContMonto();
            fila[9] = cuenta.getCuenClave();
            model.addRow(fila);
        }
        TablaPer.setModel(model);
       TableColumn  Colum=TablaPer.getColumn(Col[1]);
        Colum.setPreferredWidth(100);
        Colum=TablaPer.getColumn(Col[2]);
        Colum.setPreferredWidth(100);
        Colum=TablaPer.getColumn(Col[3]);
        Colum.setPreferredWidth(100);
        JScrollPane scroll= new JScrollPane(TablaPer);
        scroll.setPreferredSize(new Dimension(800,600));
         showMessageDialog(null,scroll,"Resultado", 1);
        
    }
    
 
    /**
    * @param args the command line arguments

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultasEurekaBank().setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jmConsultaClientes;
    private javax.swing.JMenuItem jmConsultaCuentas;
    private javax.swing.JMenuItem jmConsultaEmpleados;
    private javax.swing.JMenuItem jmConsultaMomientos;
    private javax.swing.JMenuItem jmConsultaSucursal;
    private javax.swing.JMenuItem jmListarClientes;
    private javax.swing.JMenuItem jmListarCuentas;
    private javax.swing.JMenuItem jmListarSucursales;
    private javax.swing.JMenuItem jmlistarEmpleados;
    private javax.swing.JMenuItem jmlistarmovimientos;
    // End of variables declaration//GEN-END:variables
        private ArrayList listar= new ArrayList();
}
